### ISSUE TITLE
Cannot inject implementation of interface TestTemplateInvocationContextProvider and register it as extention in Junit 5

### ISSUE THREAD

**Issue by Talankin** [micronaut-projects/micronaut-test#140]
Hello.
Cannot inject implementation of interface **TestTemplateInvocationContextProvider** to test class. 
**RegisterExtension** is finishing work before than **MyTestTemplateInvocationContextProvider's** bean was created.
So cannot register the extention

Versions:
junit-jupiter-params: 5.6.1
micronaut-test-junit5: 1.1.2
micronaut-core: 1.3.3

```java
import io.micronaut.test.annotation.MicronautTest;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.params.provider.Arguments;

import javax.inject.Inject;

import static org.junit.jupiter.api.Assertions.assertEquals;

@MicronautTest
@Slf4j
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class MyTest {

  @RegisterExtension
  @Inject
  MyTestTemplateInvocationContextProvider contextProvider;

  @TestTemplate
  void testFetchReportSuccess(Arguments arguments) {
    assertEquals(3, arguments.get().length);
    assertEquals(6, arguments.get()[1].toString().length());
  }
}
```

```java
import io.micronaut.context.annotation.Context;
import org.junit.jupiter.params.provider.Arguments;

import java.util.stream.Stream;

@Context
public class DataSupplier {

  public Stream<Arguments> getTestData() {
    return Stream.of(
      Arguments.arguments("param1", "param2", "param3"),
      Arguments.arguments("param4", "param5", "param6")
    );
  }
}
```

```java
import io.micronaut.context.annotation.Context;
import io.micronaut.context.annotation.Value;
import org.junit.jupiter.api.extension.Extension;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.api.extension.ParameterContext;
import org.junit.jupiter.api.extension.ParameterResolver;
import org.junit.jupiter.api.extension.TestTemplateInvocationContext;
import org.junit.jupiter.api.extension.TestTemplateInvocationContextProvider;
import org.junit.jupiter.params.provider.Arguments;

import java.util.Collections;
import java.util.List;
import java.util.stream.Stream;

@Context
public class MyTestTemplateInvocationContextProvider implements TestTemplateInvocationContextProvider {
  private List<String> properties;
  private DataSupplier dataSupplier;

  public MyTestTemplateInvocationContextProvider(@Value("${properties}") List<String> properties,
                                                 DataSupplier dataSupplier) {
    this.properties = properties;
    this.dataSupplier = dataSupplier;
  }

  @Override
  public boolean supportsTestTemplate(ExtensionContext context) {
    return true;
  }

  @Override
  public Stream<TestTemplateInvocationContext> provideTestTemplateInvocationContexts(
    ExtensionContext context) {
    validateProperties();
    final Stream<Arguments> testData = dataSupplier.getTestData();
    return testData.map(this::invocationContext);
  }

  private TestTemplateInvocationContext invocationContext(Arguments arguments) {
    return new TestTemplateInvocationContext() {
      @Override
      public String getDisplayName(int invocationIndex) {
        return String.format("%s", arguments.get()[0]);
      }

      @Override
      public List<Extension> getAdditionalExtensions() {
        return Collections.singletonList(new ParameterResolver() {
          @Override
          public boolean supportsParameter(ParameterContext parameterContext,
                                           ExtensionContext extensionContext) {
            return parameterContext.getParameter().getType().equals(Arguments.class);
          }

          @Override
          public Object resolveParameter(ParameterContext parameterContext,
                                         ExtensionContext extensionContext) {
            return arguments;
          }
        });
      }
    };
  }

  private void validateProperties() {
    if (properties == null) {
      throw new RuntimeException("something wrong");
    }
  }
}
```

```
Test ignored.

org.junit.platform.commons.PreconditionViolationException: Failed to register extension via @RegisterExtension field [com.path.api.MyTestTemplateInvocationContextProvider com.path.api.MyTest.contextProvider]: field value's type [null] must implement an [org.junit.jupiter.api.extension.Extension] API.

	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:296)
	at org.junit.jupiter.engine.descriptor.ExtensionUtils.lambda$registerExtensionsFromFields$2(ExtensionUtils.java:110)
	at org.junit.platform.commons.function.Try$Success.ifSuccess(Try.java:258)
	at org.junit.jupiter.engine.descriptor.ExtensionUtils.lambda$registerExtensionsFromFields$3(ExtensionUtils.java:109)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.jupiter.engine.descriptor.ExtensionUtils.registerExtensionsFromFields(ExtensionUtils.java:104)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:267)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:256)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:255)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:29)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$before$0(ClassBasedTestDescriptor.java:184)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:183)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

```

**Comment by alvarosanchez** [comment]
I could make it work with the following workaround. First of all, initialize the `contextProvider` field so that you can get past JUnit processing it:

```java
    @RegisterExtension
    @Inject
    MyTestTemplateInvocationContextProvider contextProvider = new MyTestTemplateInvocationContextProvider();
```

Also, inject the `ApplicationContext` since it will be used from the extension:

```java
    @Inject
    ApplicationContext applicationContext;
```

Then, change `MyTestTemplateInvocationContextProvider` as follows:

```java
    @Context
    public class MyTestTemplateInvocationContextProvider implements TestTemplateInvocationContextProvider {
        private List<String> properties;
        private DataSupplier dataSupplier;

        @Override
        public boolean supportsTestTemplate(ExtensionContext context) {
            if (context.getTestInstances().isPresent()) {
                Optional<RegisterExtensionTest> instance = context.getTestInstances().get().findInstance(RegisterExtensionTest.class);
                if (instance.isPresent()) {
                    ApplicationContext applicationContext = instance.get().applicationContext;
                    this.properties = new ArrayList(applicationContext.getProperties("properties").entrySet());
                    this.dataSupplier = applicationContext.getBean(DataSupplier.class);
                }
            }
            return true;
        }
        // Rest of the methods unchanged
    }
```

Then, the tests will pass as expected:

![image](https://user-images.githubusercontent.com/153880/88194278-ee85b480-cc3e-11ea-844f-f17ce072bf0f.png)
