### ISSUE TITLE
Using @Property doesn't affects value injectet using @Value

### ISSUE THREAD

**Issue by homeend** [micronaut-projects/micronaut-test#199]
Given function code:
```java
@Introspected
public class BookRequestHandler extends MicronautRequestHandler<Book, BookSaved> {
    @Value("${test}")
    String test;
    @Override
    public BookSaved execute(Book input) {
        BookSaved bookSaved = new BookSaved();
        bookSaved.setName(input.getName());
        bookSaved.setIsbn(UUID.randomUUID().toString());
        System.out.println("test: "+test);
        return bookSaved;
    }
}
```
And test file:
```java
@Property(name="test", value="xxx")
@MicronautTest(rebuildContext = true)
public class BookRequestHandlerTest {
    private static BookRequestHandler bookRequestHandler;

    @BeforeAll
    public static void setupServer() {
        bookRequestHandler = new BookRequestHandler();
    }

    @AfterAll
    public static void stopServer() {
        if (bookRequestHandler != null) {
            bookRequestHandler.getApplicationContext().close();
        }
    }

    @Test
    public void testHandler() {
        Book book = new Book();
        book.setName("Building Microservices");
        BookSaved bookSaved = bookRequestHandler.execute(book);
        assertEquals(bookSaved.getName(), book.getName());
        assertNotNull(bookSaved.getIsbn());
    }
}
```
Result is:
```
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [test] of class: site.watchdog22.BookRequestHandler

Message: Error resolving field value [${test}]. Property doesn't exist or cannot be converted
Path Taken: BookRequestHandler.test

	at io.micronaut.context.AbstractBeanDefinition.getValueForField(AbstractBeanDefinition.java:1280)
	at site.watchdog22.$BookRequestHandlerDefinition.injectBean(Unknown Source)
	at io.micronaut.context.AbstractBeanDefinition.inject(AbstractBeanDefinition.java:359)
	at io.micronaut.context.DefaultBeanContext.doInject(DefaultBeanContext.java:2144)
	at io.micronaut.context.DefaultBeanContext.inject(DefaultBeanContext.java:783)
	at io.micronaut.function.aws.MicronautRequestHandler.<init>(MicronautRequestHandler.java:49)
	at site.watchdog22.BookRequestHandler.<init>(BookRequestHandler.java:8)
	at site.watchdog22.BookRequestHandlerTest.setupServer(BookRequestHandlerTest.java:19)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeAllMethod(TimeoutExtension.java:68)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllMethods$8(ClassBasedTestDescriptor.java:375)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllMethods(ClassBasedTestDescriptor.java:373)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:193)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

If I put value in application.yml then @Property then value from application.yml is injectet, value from @Property is ignored.

Other classes to run code above:
```java
@Introspected
public class BookSaved {

    @NonNull
    @NotBlank
    private String name;

    @NonNull
    @NotBlank
    private String isbn;

    public BookSaved() {

    }

    @NonNull
    public String getName() {
        return name;
    }

    public void setName(@NonNull String name) {
        this.name = name;
    }

    @NonNull
    public String getIsbn() {
        return isbn;
    }

    public void setIsbn(@NonNull String isbn) {
        this.isbn = isbn;
    }
}

@Introspected
public class Book {

    @NonNull
    @NotBlank
    private String name;

    public Book() {
    }

    @NonNull
    public String getName() {
        return name;
    }

    public void setName(@NonNull String name) {
        this.name = name;
    }
}
```

**Comment by graemerocher** [comment]
You would need to use an injected version of `BookRequestHandler` for these properties to be injected

**Comment by homeend** [comment]
> You would need to use an injected version of `BookRequestHandler` for these properties to be injected

Try it already
```java
@Property(name="test", value="xxx")
@MicronautTest(rebuildContext = true)
public class BookRequestHandlerTest {
    @Inject
    private BookRequestHandler bookRequestHandler;
```
Results in:
```
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [test] of class: site.watchdog22.BookRequestHandler

Message: Error resolving field value [${test}]. Property doesn't exist or cannot be converted
Path Taken: BookRequestHandler.test

	at io.micronaut.context.AbstractBeanDefinition.getValueForField(AbstractBeanDefinition.java:1280)
	at site.watchdog22.$BookRequestHandlerDefinition.injectBean(Unknown Source)
	at io.micronaut.context.AbstractBeanDefinition.inject(AbstractBeanDefinition.java:359)
	at io.micronaut.context.DefaultBeanContext.doInject(DefaultBeanContext.java:2144)
	at io.micronaut.context.DefaultBeanContext.inject(DefaultBeanContext.java:783)
	at io.micronaut.function.aws.MicronautRequestHandler.<init>(MicronautRequestHandler.java:49)
	at site.watchdog22.BookRequestHandler.<init>(BookRequestHandler.java:8)
	at site.watchdog22.$BookRequestHandlerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1888)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2386)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2301)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2273)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1233)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1465)
	at io.micronaut.context.AbstractBeanDefinition.injectBeanField(AbstractBeanDefinition.java:751)
	at site.watchdog22.$BookRequestHandlerTestDefinition.injectBean(Unknown Source)
	at io.micronaut.context.AbstractBeanDefinition.inject(AbstractBeanDefinition.java:359)
	at io.micronaut.context.DefaultBeanContext.doInject(DefaultBeanContext.java:2144)
	at io.micronaut.context.DefaultBeanContext.inject(DefaultBeanContext.java:783)
	at io.micronaut.test.extensions.AbstractMicronautExtension.beforeEach(AbstractMicronautExtension.java:263)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.beforeEach(MicronautJunit5Extension.java:78)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$1(TestMethodTestDescriptor.java:161)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:197)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:197)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:160)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

Also tried this:
```java
@MicronautTest(rebuildContext = true, propertySources = "test.properties")
public class BookRequestHandlerTest {

```
Result as above.

**Comment by graemerocher** [comment]
The issue is you the handler constructs its own context that is separate from the context you are using on the test. So in effect `@MicronautTest` is not doing anything useful.

Serverless functions have to be instantiated by the function platform so they have to work this way unfortunately. The way you would pass properties to the function is to subclass it and override this method:

https://github.com/micronaut-projects/micronaut-aws/blob/master/function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestHandler.java#L92

```
    @BeforeAll
    public static void setupServer() {
        bookRequestHandler = new BookRequestHandler() {
                protected ApplicationContextBuilder newApplicationContextBuilder() {
                      return super.newApplicationContextBuilder()
                                          .properties(..); // add properties here
                }
       };
    }

```

**Comment by homeend** [comment]
Your solution worked, kind of...
> The issue is you the handler constructs its own context that is separate from the context you are using on the test.

This explains why if I try to inject some singleton bean into test class and this bean is injected into function I got two different instances, but question is how to do it ?

I have this factory, with ses mock:
```java
@Factory
@Replaces(factory = AwsClientsProvider.class)
public class AwsClientsTestcontainersProvider {
........
    @Singleton
    public AmazonSimpleEmailService ses() {
        return create_AmazonSimpleEmailService_mock();
    }
}
```
and ses() method is called twice.

Test case:
```java
@MicronautTest
public class NotExistingHostTest {
    private static SiteWatchdog2Function client;

    @BeforeAll
    public static void setupServer() {
        final Map properties = CollectionUtils.mapOf(
                "url", "http://xxxxxxxxxxxxxxxxx.com/"
        );

        client = new SiteWatchdog2Function() {
            protected ApplicationContextBuilder newApplicationContextBuilder() {
                return super.newApplicationContextBuilder()
                        .properties(properties);
            }
        };
    }

    @AfterAll
    public static void stopServer() {
        if (client != null) {
            client.getApplicationContext().close();
        }
    }

    @Inject
    AmazonSimpleEmailService ses;
...
```

Function:
```java
@Slf4j
@Introspected
public class SiteWatchdog2Function extends MicronautRequestHandler<EmptyBody, Result> {

    @Inject
    AmazonSimpleEmailService ses;

    @Value("${url}")
    String url;
```
All in all ses from SiteWatchdog2Function is different instance than from NotExistingHostTest, can you help me with that ?

**Comment by graemerocher** [comment]
You should remove `@MicronautTest` since the function manages its own context it doesn't add value to your test
