### ISSUE TITLE
BeanInstantiationException when using RxClient in Kotlin + Junit + Mockito setup

### ISSUE THREAD

**Issue by pjagielski** [micronaut-projects/micronaut-test#25]
Example repo https://github.com/pjagielski/micronaut-kotlin-junit-mockbean-problem

My test setup:

@MicronautTest
open class UsersEndpointTest {

    val embeddedServer: EmbeddedServer = ApplicationContext.run(EmbeddedServer::class.java)
    val client: RxHttpClient = RxHttpClient.create(embeddedServer.url)

    @Inject
    lateinit var userReadRepository: UserReadRepository

    @MockBean(SqlUserReadRepository::class)
    fun userReadRepository(): UserReadRepository = mock()
...
}

Gradle test output:
```
11:27:41.942 [pool-2-thread-1] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Error instantiating bean of type [io.realworld.user.domain.UserReadRepository]: No bean of type [io.realworld.user.endpoint.UsersEndpointTest] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing.
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [io.realworld.user.domain.UserReadRepository]: No bean of type [io.realworld.user.endpoint.UsersEndpointTest] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing.
    at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1335)
    at io.micronaut.context.DefaultBeanContext$1.get(DefaultBeanContext.java:1699)
    at io.micronaut.inject.ParametrizedProvider.get(ParametrizedProvider.java:45)
    at io.micronaut.runtime.context.scope.refresh.RefreshScope.lambda$get$0(RefreshScope.java:91)
    at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
    at io.micronaut.runtime.context.scope.refresh.RefreshScope.get(RefreshScope.java:90)
    at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:1692)
    at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1625)
    at io.micronaut.context.DefaultBeanContext.getProxyTargetBean(DefaultBeanContext.java:774)
    at io.realworld.user.endpoint.$UsersEndpointTest$UserReadRepositoryDefinition$Intercepted.$resolveTarget(Unknown Source)
    at io.realworld.user.endpoint.$UsersEndpointTest$UserReadRepositoryDefinition$Intercepted.interceptedTarget(Unknown Source)
    at io.realworld.user.endpoint.$UsersEndpointTest$UserReadRepositoryDefinition$Intercepted.findByEmail(Unknown Source)
    at io.realworld.security.domain.UserAuthenticationService.authenticate(UserAuthenticationService.kt:16)
```

**Comment by swarren-sumglobal** [comment]
With this same setup (Kotlin, JUnit, Mockito), I have a similar issue. While there's no exception, the mock bean doesn't get injected. The main/src impl gets injected. I have the Java equivalent (straight from the MN example) in the same project and it works correctly.

`
@MicronautTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
open class MathCollaboratorMockBeanKotlinTest {
    val embeddedServer = ApplicationContext.run(EmbeddedServer::class.java)
    val client = HttpClient.create(embeddedServer.url)

    // Injection of HttpClient fails...
    //@Inject @Client("/") lateinit var client: RxHttpClient

    @Inject
    lateinit var mathService: MathService


    @ParameterizedTest
    @CsvSource("2,4", "3,9")
    fun testComputeNumToSquare2(num: Int?, square: Int?) {

        `when`<Int>(mathService.compute(num))
                .then({ invocation -> java.lang.Long.valueOf(Math.round(Math.pow(num!!.toDouble(), 2.0))).toInt() })

        val result = client.toBlocking().retrieve(HttpRequest.GET<Any>("/math/compute/" + num!!), Int::class.java)

        assertEquals(
                square,
                result
        )
        verify<MathService>(mathService).compute(num)
    }


    @MockBean(MathServiceImpl::class)
    fun mathServiceMock(): MathService {
        return mock(MathService::class.java)
    }
}`

**Comment by carlosbarragan** [comment]
@pjagielski I have a similar set-up as yours and it works. iInstead of using `Mockito` I am using `Mockk` and also injecting the `EmbeddedServer`

```kotlin
@Inject
lateinit var server: EmbeddedServer
```

I think that could be the problem. It looks like you are explicitly starting the application which is not necessary, since `@MicronautTest` starts it already.

**Comment by swarren-sumglobal** [comment]
Using @carlosbarragan suggestion, I was able to get this working. Thanks!

```kotlin

@MicronautTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
open class MathCollaboratorMockBeanKotlinTest {

    @Inject lateinit var embeddedServer: EmbeddedServer
    //val embeddedServer = ApplicationContext.run(EmbeddedServer::class.java)

    // Injection of HttpClient fails...
    // @Inject @Client("/") lateinit var client: RxHttpClient
    lateinit var client: HttpClient

    @Inject lateinit var mathService: MathService

    @BeforeAll
    fun beforeAll() {
        client = HttpClient.create(embeddedServer.url)
    }


    @ParameterizedTest
    @CsvSource("2,4", "3,9")
    fun testComputeNumToSquare2(num: Int?, square: Int?) {

        `when`<Int>(mathService.compute(num))
                .then({ invocation -> java.lang.Long.valueOf(Math.round(Math.pow(num!!.toDouble(), 2.0))).toInt() })

        val result = client.toBlocking().retrieve(HttpRequest.GET<Any>("/math/compute/" + num!!), Int::class.java)

        assertEquals(
                square,
                result
        )
        verify<MathService>(mathService).compute(num)
    }


    @MockBean(MathServiceImpl::class)
    fun mathServiceMock(): MathService {
        return mock(MathService::class.java)
    }
} 
```
