### ISSUE TITLE
Constructor of bean mocked with @MockBean is still executed

### ISSUE THREAD

**Issue by angelyan** [micronaut-projects/micronaut-test#255]
### Steps to Reproduce

```java
public class ClassUnderTest {

    @Inject
    private final MockedBean mockedBean;
}
```

```java
@Singleton
public class MockedBean {

    private final Dependency dependency;

    @Inject
    public MockedBean(Dependency dependency) {
        this.dependency = dependency;
        dependency.shouldNotBeCalledInTests();
    }
}

```

```java
@Singleton
public class Dependency {

    private int calls;

    public void shouldNotBeCalledInTests() {
        calls++;
    }

    public int getCalls() {
        return calls;
    }
}
```

```java
@MicronautTest
class MockBeanTest {

    @Inject
    private ClassUnderTest classUnderTest;

    @Inject
    private Dependency dependency;

    @MockBean(MockedBean.class)
    MockedBean mockedBean() {
        return mock(MockedBean.class);
    }

    @Test
    void checkDependencyWasNotCalled() {
        assertEquals(0, dependency.getCalls());
    }
}
```

### Expected Behaviour

`dependency.getCalls()` should be 0.

### Actual Behaviour

`dependency.getCalls()` is 1.

### Environment Information

- **Micronaut Version:** 2.0.1
- **Micronaut Test Version:** 1.2.2
- **JDK Version:** 8

### Example Application

https://github.com/angelyan/micronaut-test-mock-dependency

### Additional notes

This does not happen when `@Singleton` and `@Replaces` are used instead of `@MockBean`:

```java
@MicronautTest
class SingletonTest {

    @Inject
    private ClassUnderTest classUnderTest;

    @Inject
    private Dependency dependency;

    @Singleton
    @Replaces(MockedBean.class)
    MockedBean mockedBean() {
        return mock(MockedBean.class);
    }

    @Test
    void checkDependencyWasNotCalled() {
        assertEquals(0, dependency.getCalls());
    }
}
```

**Comment by angelyan** [comment]
>If you subclass another class (which you do when you create a mock) the super class must be called.

If you're talking about Mockito, then that's not the case. The constructor isn't called when `mock(MockedBean.class)` is executed, otherwise the last code snippet wouldn't work. It's called when Micronaut injects the test instance, as seen in the following thread dump, before even reaching the method annotated with `@MockBean`.

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at com.example.MockedBean.<init>(MockedBean.java:14)
	  at com.example.$MockBeanTest$MockedBean0Definition$Intercepted.<init>(Unknown Source:-1)
	  at com.example.$$MockBeanTest$MockedBean0Definition$InterceptedDefinition.build(Unknown Source:-1)
	  at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1889)
	  at io.micronaut.context.DefaultBeanContext.lambda$getScopedBeanForDefinition$57(DefaultBeanContext.java:2323)
	  at io.micronaut.context.DefaultBeanContext$$Lambda$470.1217207511.apply(Unknown Source:-1)
	  at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	  - locked <0xfc4> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	  at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2316)
	  at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2298)
	  at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2270)
	  - locked <0xf72> (a java.util.concurrent.ConcurrentHashMap)
	  at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1240)
	  at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1441)
	  at io.micronaut.context.AbstractBeanDefinition.injectBeanField(AbstractBeanDefinition.java:731)
	  at com.example.$ClassUnderTestDefinition.injectBean(Unknown Source:-1)
	  at com.example.$ClassUnderTestDefinition.build(Unknown Source:-1)
	  at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1889)
	  at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2383)
	  at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2298)
	  at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2270)
	  at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1240)
	  at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1441)
	  at io.micronaut.context.AbstractBeanDefinition.injectBeanField(AbstractBeanDefinition.java:731)
	  at com.example.$MockBeanTestDefinition.injectBean(Unknown Source:-1)
	  at io.micronaut.context.AbstractBeanDefinition.inject(AbstractBeanDefinition.java:339)
	  at io.micronaut.context.DefaultBeanContext.doInject(DefaultBeanContext.java:2141)
	  at io.micronaut.context.DefaultBeanContext.inject(DefaultBeanContext.java:784)
	  at io.micronaut.test.extensions.AbstractMicronautExtension.beforeEach(AbstractMicronautExtension.java:283)
	  at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.beforeEach(MicronautJunit5Extension.java:93)
	  at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$1(TestMethodTestDescriptor.java:161)
```

**Comment by graemerocher** [comment]
right, understood `@MockBean` is slightly different as it has to manage the lifecycle of the mock and rest it state between tests. Using `@Replaces` is the way to go if you don't want this behaviour

**Comment by angelyan** [comment]
The downside of using `@Singleton` + `@Replaces` is that the mock is not reset anymore.

Instead of defining `@MockBean` as `@Refreshable`, wouldn't it be possible to define it as `@Singleton` and to destroy the bean before injecting each test instance in order to reset it? This seems to work in JUnit but I'm not sure if it'll break something else.

**Comment by KDanisme** [comment]
Is there still no fix for this?
AFAIK this is the current behaviour aswell.
Currently, my unittests cannot run by themselfs, I need to mock a bean that is trying to connect to a database, and it fails.

So sadly i have to use my integration test setup for my unit test setup, aswell.
