### ISSUE TITLE
parallel test execution throws ConcurrentModificationException 

### ISSUE THREAD

**Issue by vmj** [micronaut-projects/micronaut-test#322]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Generate a minimal application: `mn create-app -b=gradle --jdk=11 -l=java -t=spock demo`
1. Change into `demo`: `cd demo`
1. Overwrite the spock version in `build.gradle`: `testImplementation("org.spockframework:spock-core:2.0-M4-groovy-3.0")`
1. Make test resources directory: `mkdir -p src/test/resources`
1. Enable parallel test execution by adding file `src/test/resources/SpockConfig.groovy`:
    ```groovy
    runner {
        parallel {
            enabled true
        }
    }
    ```
1. Make the example test run a few times, e.g. by adding a `where` block:
    ```groovy
    @MicronautTest
    class DemoSpec extends Specification {

        @Inject
        EmbeddedApplication<?> application

        void 'test it works'() {
            expect:
            application.running

            where:
            id << (0..100).asList()
        }
    }
    ```
1. Run the tests: `./gradlew --no-build-cache clean test`

### Expected Behaviour

Tests should pass.  I.e. `BUILD SUCCESSFUL`.

### Actual Behaviour

About 3 out of 5 times some of the tests fail with the following error:

```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.compute(HashMap.java:1229)
	at io.micronaut.test.extensions.AbstractMicronautExtension.beforeEach(AbstractMicronautExtension.java:253)
	at io.micronaut.test.extensions.spock.MicronautSpockExtension.lambda$visitSpecAnnotation$5(MicronautSpockExtension.java:133)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:101)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:136)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

Seems to refer to `testProperties` field in `AbstractMicronautExtension` class.

### Environment Information

- **Operating System**: macOS 10.15.7
- **Micronaut Version:** 2.1.2
- **JDK Version:** 
    ```
    openjdk version "11.0.9" 2020-10-20 LTS
    OpenJDK Runtime Environment Zulu11.43+21-CA (build 11.0.9+11-LTS)
    OpenJDK 64-Bit Server VM Zulu11.43+21-CA (build 11.0.9+11-LTS, mixed mode)
    ```

**Comment by alvarosanchez** [comment]
I guess [this maps](https://github.com/micronaut-projects/micronaut-test/blob/master/test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java#L70-L71) could be changed to `ConcurrentHashMap`s.

**Comment by graemerocher** [comment]
I'm not sure these extensions are designed to be concurrently executed, and not sure I understand what Gradle's parallel test support is allowing parallel access to extensions

**Comment by vmj** [comment]
> I'm not sure these extensions are designed to be concurrently executed, and not sure I understand why Gradle's parallel test support is allowing parallel access to extensions

You probably meant Spock's parallel execution.  It's a new feature in Spock 2.0 M4.

Yes, there's a larger question of how spock extensions should be implemented to support it.

**Comment by ecmel** [comment]
JUnit parallel test execution also fails.
