### ISSUE TITLE
HTTP Client fails with NoHostException

### ISSUE THREAD

**Issue by vnesek** [micronaut-projects/micronaut-test#347]
When trying to use injected HttpClient I keep getting NoHostException no matter what I try to do. 
I guess it's some trivial configuration detail I'm missing.

### Steps to Reproduce

Using:
```kotlin
    kaptTest("io.micronaut:micronaut-inject")
    testImplementation("org.junit.jupiter:junit-jupiter-api")
    testImplementation("io.micronaut.test:micronaut-test-junit5:2.2.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.7.0")

```

Run test:

```kotlin
package foo

import io.micronaut.http.HttpStatus.OK
import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get
import io.micronaut.http.client.HttpClient
import io.micronaut.http.client.annotation.Client
import io.micronaut.test.extensions.junit5.annotation.MicronautTest
import kotlinx.coroutines.reactive.awaitFirst
import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test
import javax.inject.Inject

data class FooData(
    val foo: String
)

@Controller("/foo")
class FooController {

    @Get
    fun testIt() = FooData("bar")
}

@MicronautTest
class FooTest {

    @Client("/")
    @Inject
    lateinit var client: HttpClient

    @Test
    fun testIt() = runBlocking {
        val result = client.exchange("/foo", FooData::class.java).awaitFirst()
        assertEquals(OK, result.status)
        val body = result.body()
        assertNotNull(body)
        assertEquals("bar", body?.foo)
    }
}
```

Fails with exception:

```
Request URI specifies no host to connect to
io.micronaut.http.client.exceptions.NoHostException: Request URI specifies no host to connect to
	at io.micronaut.http.client.netty.DefaultHttpClient.resolveRequestURI(DefaultHttpClient.java:1213)
	at io.micronaut.http.client.netty.DefaultHttpClient.resolveRequestURI(DefaultHttpClient.java:1197)
	at io.micronaut.http.client.netty.DefaultHttpClient.exchange(DefaultHttpClient.java:710)
	at io.micronaut.http.client.netty.DefaultHttpClient.exchange(DefaultHttpClient.java:161)
	at io.micronaut.http.client.HttpClient.exchange(HttpClient.java:89)
	at io.micronaut.http.client.RxHttpClient.exchange(RxHttpClient.java:37)
	at io.micronaut.http.client.RxHttpClient.exchange(RxHttpClient.java:33)
	at io.micronaut.http.client.HttpClient.exchange(HttpClient.java:125)
	at io.micronaut.http.client.RxHttpClient.exchange(RxHttpClient.java:60)
	at io.micronaut.http.client.RxHttpClient.exchange(RxHttpClient.java:33)
	at foo.FooTest$testIt$1.invokeSuspend(FooTest.kt:37)
	(Coroutine boundary)
	at foo.FooTest$testIt$1.invokeSuspend(FooTest.kt:37)
	(Coroutine creation stacktrace)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.createCoroutineUnintercepted(IntrinsicsJvm.kt:122)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at foo.FooTest.testIt(FooTest.kt:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestMethod(InvocationInterceptor.java:117)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
```

### Expected Behaviour

Test passes.

### Actual Behaviour

Test fails with NoHostException.

### Environment Information

- **Operating System**: macOS
- **Micronaut Version:** 2.2.1
- **JDK Version:** 11

**Comment by graemerocher** [comment]
With Kotlin it has to be `@field:Client("/")`
