### ISSUE TITLE
Spock test with @MicronautTest failed - Failed to inject value for parameter [objectMapper]

### ISSUE THREAD

**Issue by thermech** [micronaut-projects/micronaut-test#4]
I try to add the @MicronautTest to my test and I got this error:

```
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [objectMapper] of class: io.micronaut.jackson.convert.ArrayNodeToArrayConverter

Message: Multiple possible bean candidates found: [com.fasterxml.jackson.databind.ObjectMapper, com.fasterxml.jackson.databind.ObjectMapper]
Path Taken: new ArrayNodeToArrayConverter([ObjectMapper objectMapper])

	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1282)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2171)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2102)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:751)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:521)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:312)
	at io.micronaut.context.DefaultApplicationContext.initializeTypeConverters(DefaultApplicationContext.java:330)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:184)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:1970)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:155)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:138)
	at io.micronaut.context.ApplicationContextBuilder.start(ApplicationContextBuilder.java:120)
	at io.micronaut.context.ApplicationContext.run(ApplicationContext.java:221)
	at io.micronaut.context.ApplicationContext.run(ApplicationContext.java:202)
	at io.micronaut.context.ApplicationContext.run(ApplicationContext.java:185)
	at example.micronaut.BooksControllerSpec.$spock_initializeSharedFields(BooksControllerSpec.groovy:18)
Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [com.fasterxml.jackson.databind.ObjectMapper, com.fasterxml.jackson.databind.ObjectMapper]
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:1354)
	at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:313)
	at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:1829)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:1770)
	at io.micronaut.context.DefaultBeanContext.lambda$findConcreteCandidate$47(DefaultBeanContext.java:1719)
	at io.micronaut.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2034)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1892)
	at io.micronaut.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2032)
	at io.micronaut.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2015)
	at io.micronaut.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
	at io.micronaut.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:1718)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1529)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:883)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:973)
	... 16 more
```

My gradle dependencies:

```
dependencies {
    compile "io.micronaut:runtime-groovy"
    compile "io.micronaut:validation"
    compile "io.micronaut:http-client"
    compile "io.micronaut:http-server-netty"
    compileOnly "io.micronaut:inject-groovy"
    compile group: 'io.micronaut.test', name: 'micronaut-test-spock', version: '1.0.0.RC1'
    runtime "ch.qos.logback:logback-classic:1.2.3"
    testCompile "io.micronaut:inject-groovy"
    testCompile("org.spockframework:spock-core:1.2-groovy-2.4") {
        exclude group: "org.codehaus.groovy", module: "groovy-all"
    }
}
```

My test:

```
@MicronautTest
class MyObjectSpec extends Specification {
    void "some test"() {
       //....
    }
}
```

**Comment by graemerocher** [comment]
What version of Micronaut are you using?

**Comment by graemerocher** [comment]
looks like you need to upgrade to Micronaut 1.0.0

**Comment by thermech** [comment]
🤔 It's not yet available on mavencentral nor on https://dl.bintray.com/micronaut/core-releases-local

**Comment by graemerocher** [comment]
See https://docs.micronaut.io/latest/guide/index.html#breaks

dependencies now start with `micronaut-`: https://search.maven.org/artifact/io.micronaut/micronaut-core/1.0.0/jar

**Comment by thermech** [comment]
With Micronaut 1.0.0 the problem is fixed

Thanks @graemerocher
