### ISSUE TITLE
MicronautTest trying to load classes in src/test of 3rd party dependencies

### ISSUE THREAD

**Issue by subash89** [micronaut-projects/micronaut-test#707]
### Issue description
In my micronaut jaxrs project-A pom.xml, I have defined project-B as a dependency. 
As follows, it tries to load  a class in package "com.myapp.junit5.aws" which is a class in project-B/src/test folder. Why micronaut trying to load those test package classes ?

`
Caused by: java.lang.NoClassDefFoundError: **software/amazon/awssdk/services/firehose/FirehoseAsyncClient**
	at com.myapp.junit5.aws.$FirehoseTestResource$Definition.<clinit>(Unknown Source)
	at com.myapp.junit5.aws.$FirehoseTestResource$Definition$Reference.load(Unknown Source)
	at io.micronaut.context.AbstractInitializableBeanDefinitionReference.load(AbstractInitializableBeanDefinitionReference.java:145)
	at io.micronaut.context.DefaultBeanContext.lambda$getBeanDefinitions$17(DefaultBeanContext.java:1503)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue$CLQSpliterator.forEachRemaining(ConcurrentLinkedQueue.java:894)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.micronaut.context.DefaultBeanContext.getBeanDefinitions(DefaultBeanContext.java:1506)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:64)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:44)
	at io.micronaut.context.DefaultBeanContext.triggerBeanCreatedEventListener(DefaultBeanContext.java:2407)
	at io.micronaut.context.DefaultBeanContext.postBeanCreated(DefaultBeanContext.java:2385)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2309)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918)
`

**Comment by subash89** [comment]
Please note that I update the subject of the issue and content substantially bit more to make it more clean and simple as it was originally.

**Comment by subash89** [comment]
When trying to replicate this issue on a simpler example project, found out that those 3rd party dependencies marked as provided, then micronaut try to package them. When I remove the provided scope from those 3rd party dependencies, then micronaut avoid packaging/loading those inside src/test.
