### ISSUE TITLE
Using eagerInitSingletons in an ApplicationContextConfigurer breaks injecting an httpclient into tests

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-test#715]
### Issue description

Micronaut CRaC adds a context configurer to eagerly initialize singletons:

```java
    @ContextConfigurer
    public static class Configurer implements ApplicationContextConfigurer {
        @Override
        public void configure(@NonNull ApplicationContextBuilder builder) {
            builder.eagerInitSingletons(true);
        }
    }
```

However when this is applied, if you add a controller to a plain 3.8.4 app:

```java
package example.micronaut;

import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;

import java.util.Collections;
import java.util.Map;

@Controller 
public class HelloController {
    @Get
    public Map<String, Object> index() {
        return Collections.singletonMap("message", "Hello World"); 
    }
}
```

and a test: 

```java
package example.micronaut;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import io.micronaut.http.HttpRequest;
import io.micronaut.http.client.HttpClient;
import io.micronaut.http.client.annotation.Client;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import org.junit.jupiter.api.Test;

import jakarta.inject.Inject;
import org.junit.jupiter.api.Disabled;

@MicronautTest // <1>
public class HelloControllerTest {

    @Inject
    @Client("/")  // <2>
    HttpClient client;

    @Test
    public void testHello() {
        String body = client.toBlocking().retrieve(HttpRequest.GET("/"));
        assertNotNull(body);
        assertEquals("{\"message\":\"Hello World\"}", body);
    }
}

```

Test fails with:

```
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [example.micronaut.HelloControllerTest] could not be loaded: Error instantiating bean of type  [example.micronaut.HelloControllerTest]

Message: Retrieving the port from the server before it has started is not supported when binding to a random port
Path Taken: new HelloControllerTest() --> HelloControllerTest.client
	at app//io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1921)
	at app//io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:249)
	at app//io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3326)
	at app//io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3684)
	at app//io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:341)
	at app//io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:194)
	at app//io.micronaut.test.extensions.AbstractMicronautExtension.startApplicationContext(AbstractMicronautExtension.java:433)
	at app//io.micronaut.test.extensions.AbstractMicronautExtension.beforeClass(AbstractMicronautExtension.java:314)
	at app//io.micronaut.test.extensions.junit5.MicronautJunit5Extension.beforeAll(MicronautJunit5Extension.java:84)
	at app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:395)
	at app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:211)
	at app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@19.0.2/java.util.ArrayList.forEach(ArrayList.java:1511)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at app//org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at app//org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base@19.0.2/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base@19.0.2/java.lang.reflect.Method.invoke(Method.java:578)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [example.micronaut.HelloControllerTest]
```

Micronaut Framework: 3.8.4

[bugcractest.zip](https://github.com/micronaut-projects/micronaut-crac/files/10722071/bugcractest.zip)

**Comment by timyates** [comment]
Got a failing test

```diff
diff --git a/test-junit5/src/test/java/io/micronaut/test/junit5/EagerSingletonTest.java b/test-junit5/src/test/java/io/micronaut/test/junit5/EagerSingletonTest.java
index 3268a262..90d5cfae 100644
--- a/test-junit5/src/test/java/io/micronaut/test/junit5/EagerSingletonTest.java
+++ b/test-junit5/src/test/java/io/micronaut/test/junit5/EagerSingletonTest.java
@@ -1,2 +1,48 @@
-package io.micronaut.test.junit5;public class EagerSingletonTest {
+package io.micronaut.test.junit5;
+
+import io.micronaut.context.ApplicationContextBuilder;
+import io.micronaut.context.ApplicationContextConfigurer;
+import io.micronaut.context.annotation.ContextConfigurer;
+import io.micronaut.context.annotation.Property;
+import io.micronaut.context.annotation.Requires;
+import io.micronaut.core.annotation.NonNull;
+import io.micronaut.http.annotation.Controller;
+import io.micronaut.http.annotation.Get;
+import io.micronaut.http.client.HttpClient;
+import io.micronaut.http.client.annotation.Client;
+import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
+import jakarta.inject.Inject;
+import org.junit.jupiter.api.Assertions;
+import org.junit.jupiter.api.Test;
+
+@MicronautTest
+@Property(name = "spec.name", value = "EagerSingletonTest")
+class EagerSingletonTest {
+
+    @Inject
+    @Client("/")
+    HttpClient client;
+
+    @Test
+    void testEagerSingleton() {
+        Assertions.assertEquals("eager", client.toBlocking().retrieve("/eager"));
+    }
+
+    @Requires(property = "spec.name", value = "EagerSingletonTest")
+    @ContextConfigurer
+    public static class Configurer implements ApplicationContextConfigurer {
+        @Override
+        public void configure(@NonNull ApplicationContextBuilder builder) {
+            builder.eagerInitSingletons(true);
+        }
+    }
+
+    @Requires(property = "spec.name", value = "EagerSingletonTest")
+    @Controller("/eager")
+    public static class EagerController {
+        @Get
+        String test() {
+            return "eager";
+        }
+    }
 }
```

**Comment by timyates** [comment]
Of course it works if you don't inject the client:

```
    Supplier<BlockingHttpClient> client() {
        return SupplierUtil.memoized(() -> embeddedServer.getApplicationContext().createBean(HttpClient.class, embeddedServer.getURL()).toBlocking());
    }
```

**Comment by sdelamo** [comment]
> Got a failing test
> 
> ```diff
> diff --git a/test-junit5/src/test/java/io/micronaut/test/junit5/EagerSingletonTest.java b/test-junit5/src/test/java/io/micronaut/test/junit5/EagerSingletonTest.java
> index 3268a262..90d5cfae 100644
> --- a/test-junit5/src/test/java/io/micronaut/test/junit5/EagerSingletonTest.java
> +++ b/test-junit5/src/test/java/io/micronaut/test/junit5/EagerSingletonTest.java
> @@ -1,2 +1,48 @@
> -package io.micronaut.test.junit5;public class EagerSingletonTest {
> +package io.micronaut.test.junit5;
> +
> +import io.micronaut.context.ApplicationContextBuilder;
> +import io.micronaut.context.ApplicationContextConfigurer;
> +import io.micronaut.context.annotation.ContextConfigurer;
> +import io.micronaut.context.annotation.Property;
> +import io.micronaut.context.annotation.Requires;
> +import io.micronaut.core.annotation.NonNull;
> +import io.micronaut.http.annotation.Controller;
> +import io.micronaut.http.annotation.Get;
> +import io.micronaut.http.client.HttpClient;
> +import io.micronaut.http.client.annotation.Client;
> +import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
> +import jakarta.inject.Inject;
> +import org.junit.jupiter.api.Assertions;
> +import org.junit.jupiter.api.Test;
> +
> +@MicronautTest
> +@Property(name = "spec.name", value = "EagerSingletonTest")
> +class EagerSingletonTest {
> +
> +    @Inject
> +    @Client("/")
> +    HttpClient client;
> +
> +    @Test
> +    void testEagerSingleton() {
> +        Assertions.assertEquals("eager", client.toBlocking().retrieve("/eager"));
> +    }
> +
> +    @Requires(property = "spec.name", value = "EagerSingletonTest")
> +    @ContextConfigurer
> +    public static class Configurer implements ApplicationContextConfigurer {
> +        @Override
> +        public void configure(@NonNull ApplicationContextBuilder builder) {
> +            builder.eagerInitSingletons(true);
> +        }
> +    }
> +
> +    @Requires(property = "spec.name", value = "EagerSingletonTest")
> +    @Controller("/eager")
> +    public static class EagerController {
> +        @Get
> +        String test() {
> +            return "eager";
> +        }
> +    }
>  }
> ```

Can you add the test with `@PendingFeature` to the test suite.
