### ISSUE TITLE
ParameterResolutionException when using BiConsumer with @ParameterizedTest

### ISSUE THREAD

**Issue by tthach-bdc** [micronaut-projects/micronaut-test#988]
### Expected Behavior

I have a basic test which uses a `BiConsumer` as an argument in a `ParameterizedTest`:

```
package sandbox;

import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.function.BiConsumer;
import java.util.stream.Stream;

import static org.junit.jupiter.params.provider.Arguments.arguments;

@MicronautTest
public class MicronautJUnitTest {
    private static final Logger LOG = LoggerFactory.getLogger(MicronautJUnitTest.class);

    public static Stream<Arguments> testWithParameterizedTest() {
        return Stream.of(
                arguments(
                        (BiConsumer<String, String>) (ols, cs) -> {},
                        1)
        );
    }

    @ParameterizedTest
    @MethodSource
    public void testWithParameterizedTest(BiConsumer<String, String> biConsumer, int one) {
        LOG.info("biConsumer = {}; one = {}", biConsumer, one);
    }
}

```

It should just log when run. If I remove the `@MicronautTest` the test runs successfully.

### Actual Behaviour

I get a `ParameterResolutionException`:
```
org.junit.jupiter.api.extension.ParameterResolutionException: Discovered multiple competing ParameterResolvers for parameter [java.util.function.BiConsumer<com.bill.organization.application.service.auth.OrganizationLoginService, com.bill.platform.common.http.json.CookieService> arg0] in method [public void com.bill.organization.api.json.settings.JUnitNoMicronautTest.testWithParameterizedTest(java.util.function.BiConsumer<com.bill.organization.application.service.auth.OrganizationLoginService, com.bill.platform.common.http.json.CookieService>,int)]: io.micronaut.test.extensions.junit5.MicronautJunit5Extension@3e34ace1, org.junit.jupiter.params.ParameterizedTestParameterResolver@62fe6067

	at org.junit.jupiter.engine.execution.ParameterResolutionUtils.resolveParameter(ParameterResolutionUtils.java:131)
	at org.junit.jupiter.engine.execution.ParameterResolutionUtils.resolveParameters(ParameterResolutionUtils.java:103)
	at org.junit.jupiter.engine.execution.ParameterResolutionUtils.resolveParameters(ParameterResolutionUtils.java:64)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:84)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:226)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:204)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:142)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.lambda$execute$2(TestTemplateTestDescriptor.java:110)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
```

### Steps To Reproduce

1. I'm using IntelliJ to write and run my test on a MacBook Pro, Ventura 13.6.6
2. I run the test as a JUnit test. This is my run config:
![Screenshot 2024-03-29 at 10 07 55 AM](https://github.com/micronaut-projects/micronaut-test/assets/59661704/1dbeb16f-8764-4eea-9c92-e065caf11b18)

### Environment Information

- OS: MacBook Pro, Ventura 13.6.6
- JDK: JDK 17 Correto

### Version

3.9.2

**Comment by sdelamo** [comment]
have you tried: `@MicronautTest(resolveParameters = false)`?

> By default, with JUnit 5 the test method parameters will be resolved to beans if possible. As this behaviour can be problematic if in combination with the @ParameterizedTest annotation, it can be disabled.

https://micronaut-projects.github.io/micronaut-test/4.3.0/guide/#junit5TestMethodsInjection

**Comment by timyates** [comment]
So the issue here (as @sdelamo points out) is that we have 2 competing things trying to resolve the parameters...

The JUnit parameterized resolver and the micronaut test resolver (which is used to inject beans)

This usually works seamlessly, until we get to something that is in both Micronaut AND the parameterized Stream.

And `DefaultTaskExceptionHandler` is a BiConsumer, which is why this falls down...

The workaround here is to do as said by Sergio, and turn off parameter resolution for this test, and use field injection with `@Inject` for any micronaut beans you require, eg:

```java
@MicronautTest(resolveParameters = false)
class ParameterizedTestTest {

    @Inject
    @Client("/")
    HttpClient client;

    public static Stream<Arguments> testWithParameterizedTest() {
        return Stream.of(
            arguments((BiConsumer<Integer, Integer>) (a, b) -> {
                System.out.println("a = " + a + ", b = " + b);
            }, 1, 2)
        );
    }

    @ParameterizedTest
    @MethodSource
    void testWithParameterizedTest(BiConsumer<Integer, Integer> op, int value, int expected) {
        assertNotNull(client);
        op.accept(value, expected);
    }
}
```

Or another workaround is to alias the BiConsumer with your own type as so:

```java
@MicronautTest
class ParameterizedTestTest {

    public static Stream<Arguments> testWithParameterizedTest() {
        return Stream.of(
            arguments((MyConsumer<Integer, Integer>) (a, b) -> {
                System.out.println("a = " + a + ", b = " + b);
            }, 1, 2)
        );
    }

    @ParameterizedTest
    @MethodSource
    void testWithParameterizedTest(MyConsumer<Integer, Integer> op, int value, int expected, @Client("/") HttpClient client) {
        assertNotNull(client);
        op.accept(value, expected);
    }

    @FunctionalInterface
    private interface MyConsumer<T, U> extends BiConsumer<T, U> {
    }
}
```

We *could* detect `@ParameterizedTest` methods, and introduce a new annotation to specify that a parameter should be injected from the micronaut context, but this would be a breaking change and would require more thought...

**Comment by sdelamo** [comment]
@tthach-bdc use 


```java
 @MicronautTest(resolveParameters = false)
 MyTest {
 
 @Inject
 MyCollaborator collaborator;
 
    @ParameterizedTest
    @MethodSource
    public void testWithParameterizedTest(BiConsumer<String, String> biConsumer, int one) {
 }
 ```
